- name: Download Docker Compose binary
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Verify docker-compose installation
  command: docker-compose --version
